spring.application.name=backend

# MySQL Configuration
# --------------
spring.datasource.url=jdbc:mysql://127.0.0.1:3309/db_pdfmaker?useSSL=false
spring.datasource.username=userPdfMaker#
spring.datasource.password=userPdfMaker#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# Mongodb Configuration
# --------------
spring.data.mongodb.uri=mongodb://pdf_maker_user:pdf_maker_pass@localhost:27017/pdf_maker_mongo
server.port=8080
spring.security.user.name=admin
spring.security.user.password=admin


# Multipart file upload configuration
#-------------------------------
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT Configuration
#-------------------------------
security.jwt.secret-key=Rm2K0JzYmyuwGJcggmHi7QUsynrLlayIdnIENVXDcQ9
security.jwt.expiration=86400000
security.jwt.refresh-expiration=604800000


# Dossier coffre fort

coffre.download.folder-name=MonCoffreFort/